// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTvmYilwt7c1f-0rzDOY3pkb_zg_Tb-8',
    appId: '1:276873302092:web:17ce8a2a56326a3a1264e9',
    messagingSenderId: '276873302092',
    projectId: 'schedule-10688',
    authDomain: 'schedule-10688.firebaseapp.com',
    storageBucket: 'schedule-10688.firebasestorage.app',
    measurementId: 'G-41VYKTJSW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHR93WTcwW_w-zQjFx0C-4yku1uoN1UkY',
    appId: '1:276873302092:android:69a02b416e7328ce1264e9',
    messagingSenderId: '276873302092',
    projectId: 'schedule-10688',
    storageBucket: 'schedule-10688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6p6NE4v6jHM7u1x-h_IFIYWWD8bB4y6Y',
    appId: '1:276873302092:ios:141c13531a3bf2321264e9',
    messagingSenderId: '276873302092',
    projectId: 'schedule-10688',
    storageBucket: 'schedule-10688.firebasestorage.app',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6p6NE4v6jHM7u1x-h_IFIYWWD8bB4y6Y',
    appId: '1:276873302092:ios:141c13531a3bf2321264e9',
    messagingSenderId: '276873302092',
    projectId: 'schedule-10688',
    storageBucket: 'schedule-10688.firebasestorage.app',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKTvmYilwt7c1f-0rzDOY3pkb_zg_Tb-8',
    appId: '1:276873302092:web:0449b3d154ccbf591264e9',
    messagingSenderId: '276873302092',
    projectId: 'schedule-10688',
    authDomain: 'schedule-10688.firebaseapp.com',
    storageBucket: 'schedule-10688.firebasestorage.app',
    measurementId: 'G-MPMLDL0JPR',
  );
}
